### PR TITLE
Build Gazebo w/ Dart

### PR DESCRIPTION
**Pull request by pattacini**

### CODE REVIEW

**Comment by traversaro** [comment]
cc @diegoferigo @giulioromualdi

**Comment by GiulioRomualdi** [comment]
@xenvre

**Comment by traversaro** [comment]
By the way, for something like the vvv-school image, eventually it may be better to switch to use a tag or commit rather then a branch, otherwise if there is some regression in `gazebo11` this could be reflected in problems in our image in a non deterministic way, depending on when the image was built.

**Comment by pattacini** [comment]
Correct @traversaro 👍🏻 
Done in cbb51bbc9f4b747e144738370aae52e2167539e7.

**Pull request merged**
